# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  org.opencontainers.image.title: "1Password for Home Assistant"
  org.opencontainers.image.description: "Sync your secrets from 1password"
  org.opencontainers.image.source: "https://github.com/Borales/hassio-addons"
  org.opencontainers.image.licenses: "MIT License"
