name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2

      - name: 🔍 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./${{ matrix.path }}/web/.nvmrc"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "./${{ matrix.path }}/web/package.json"
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: "./${{ matrix.path }}/web"

      - name: Run lint
        run: pnpm lint
        working-directory: "./${{ matrix.path }}/web"

      - name: Run test coverage
        run: pnpm test:coverage
        working-directory: "./${{ matrix.path }}/web"

      - name: Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.21
        with:
          path: "./${{ matrix.path }}"
